-- ARQUIVO LEGADO DESATIVADO.
-- NÃO EXECUTAR NO SUPABASE.
--
-- Este arquivo continha políticas que permitiam acesso público às lojas.
-- Essas políticas foram substituídas pelo isolamento por usuário.
--
-- Histórico da migração já aplicada:
-- database/supabase-migrations/001-lojas-por-usuario.sql
--
-- Para preparar um banco novo, será necessário criar um script atualizado
-- que inclua usuario_id, RLS e permissões restritas.
-- Não reutilize as definições antigas deste arquivo.